### ISSUE TITLE
FGB Board is down

### ISSUE THREAD

**Issue by dotis** [marinebon/mbon-dashboard-server#64]
The others are fine. Perhaps a docker issue?

**Comment by 7yl4r** [comment]
Something seems to have gone wrong with the google cloud VM. When trying to connect I get a "firewall blocking port 22" error, which is nonsense. The port has never been closed and I confirmed that with the network firewall manager. Unless we somehow accidentally enabled a different firewall on the node. I haven't modified anything to do with the firewall since setup, and even then I just copied it from the other VMs.

I shut down the VM using the gcloud console then started it again.
After doing this I was able to SSH in again and everything looked okay in the output of `docker container ls -a`. I ran a `docker compose up --build -d` just in case. With any luck things will be back up in ~15min.

**Comment by dotis** [comment]
The changes have now been pushed from the json file. Thanks @7yl4r 

However, the .csv files are not updated. The DAG seems fine. The files in the data bucket are updated and have yesterday as the last date, but the dash only shows data through early December. This may be similar to the issue we had before with the ingest script. This happened when we were dealing with the negative numbers for time on the first line of the csv files. I think that the ingest script may have been changed for the other boards, but not FWC.
